FileVersion = 1

[Project]
Name = "tinycthread-beef"
DefaultNamespace = "tinycthread"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\tinycthread.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\tinycthread.lib"]
